#!/bin/sh

#Autostart
killall sxhkd; sxhkd &
feh --bg-fill -r -z $HOME/Pictures/Wallpapers &
xsetroot -cursor_name left_ptr &

#variable
alias bc='bspc config'
alias br='bspc rule'
c="#1f1f1f"

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7

#Others
bc border_width 0
bc normal_border_color "$c"
bc focused_border_color "$c"
bc active_border_color "$c"
bc window_gap 10
bc split_ratio 0.50
bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true

#rules
br -a Lxappearance state=floating
br -a feh state=floating
br -a mpv state=floating
